name: Actions Workflow

on: [push] # define events that should trigger the workflow

# to enable additional logging for debug purposes, go to repo -> Settings -> Secrets -> new repo secret
# add ACTIONS_RUNNER_DEBUG, set it to `true` (runner level)
# add ACTIONS_STEP_DEBUG, set it to `true` (debug each step)
jobs:
  # job's name
  run-github-actions: # jobs are run in parallel unless you define dependencies on other jobs via 'jobs.<job_id>.needs'
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls
      - name: Simple js action
        id: greet
        # can reference actions defined locally via ./... or from some repository
        uses: actions/hello-world-javascript-action@v1 # @<n>: n - specify a version/branch/commit_id (version is preferable)
        with: # provide some input for the action
          who-to-greet: John
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}" # call the output of the action with id `greet`
